### PR TITLE
feat: added

### PR DESCRIPTION
**Pull request by RickDeb2004**
#23 
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by MAVRICK-1** [comment]
@RickDeb2004 make it responsive and add some styling

**Comment by RickDeb2004** [comment]
> #23
> 
> ## Description
> ## Motivation and Context
> ## How Has This Been Tested?
> ## Screenshots (if appropriate):
> ## Types of changes
> * [ ]  Bug fix (non-breaking change which fixes an issue)
> * [ ]  New feature (non-breaking change which adds functionality)
> * [ ]  Breaking change (fix or feature that would cause existing functionality to change)
> 
> ## Checklist:
> * [ ]  My code follows the code style of this project.
> * [ ]  My change requires a change to the documentation.
> * [ ]  I have updated the documentation accordingly.

image
mobile view:
image

**Comment by MAVRICK-1** [comment]
Thik lag raha hum badmaay Thora change kardegay merging this

**Pull request merged**
