### PR TITLE
feat: added seller sign-up

### PR DESCRIPTION
**Pull request by RickDeb2004**
close: #7 && #6 
## Description

still left to design , will do it by EOD
image
image

### CODE REVIEW

**Comment by MAVRICK-1** [comment]
@RickDeb2004  You didn't make new form ,u just changed the existing one

**Comment by RickDeb2004** [comment]
> @RickDeb2004  You didn't make new form ,u just changed the existing one. Form ka layout copy karke naya component bana
> 

Will render both in same component..that would be good approach

**Comment by MAVRICK-1** [comment]
Okay 👍

**Comment by RickDeb2004** [comment]
@MAVRICK-1

**Comment by MAVRICK-1** [comment]
Okay I will check it by today , it looks good

**Comment by RickDeb2004** [comment]
merge this one
@MAVRICK-1

**Pull request closed without merging**
